### PR TITLE
GitHub Action setup

### PR DESCRIPTION
**Pull request by imciner2**
Testing and setting up a GitHub actions flow for this repo.

### CODE REVIEW

**Comment by EdwardStables** [comment]
I've setup the basic tests and docs to confirm it's all working, seems to be good.

**Comment by imciner2** [comment]
Did you base these on the workflows I made inside https://github.com/ImperialCollegeLondon/DirectSearch.jl? I had made some changes to these flows when I made the one for the direct search package and was going to move those over to here once the tests were fixed.

**Comment by EdwardStables** [comment]
The documentation workflow is identical to that used by directsearch, but the ci workflow is unchanged from that in the initial pull request.

**Comment by EdwardStables** [comment]
I don't have access to the repo settings to configure github pages to host the docs. Could you set that up @imciner2 ?

**Pull request merged**
